(function () {
    'use strict';

    var KeyCode = {};
    KeyCode.NUM_0       = 48;
    KeyCode.NUM_1       = 49;
    KeyCode.NUM_2       = 50;
    KeyCode.NUM_3       = 51;
    KeyCode.NUM_4       = 52;
    KeyCode.NUM_5       = 53;
    KeyCode.NUM_6       = 54;
    KeyCode.NUM_7       = 55;
    KeyCode.NUM_8       = 56;
    KeyCode.NUM_9       = 57;
    KeyCode.SPACE       = 32;
    KeyCode.BACK_SPACE  = 8;
    KeyCode.ENTER       = 13;
    KeyCode.SHIFT       = 16;
    KeyCode.CTRL        = 17;
    KeyCode.ALT         = 18;
    KeyCode.ESC         = 27;
    KeyCode.LEFT_ARROW  = 37;
    KeyCode.RIGHT_ARROW = 39;
    KeyCode.UP_ARROW    = 39;
    KeyCode.DOWN_ARROW  = 40;
    KeyCode.DELETE      = 46;
    KeyCode.F1          = 112;
    KeyCode.F2          = 113;
    KeyCode.F3          = 114;
    KeyCode.F4          = 115;
    KeyCode.Q           = 81;
    KeyCode.W           = 87;
    KeyCode.E           = 69;
    KeyCode.R           = 82;
    KeyCode.A           = 65;
    KeyCode.S           = 83;
    KeyCode.D           = 68;
    KeyCode.F           = 70;
    KeyCode.Z           = 90;
    KeyCode.X           = 88;
    KeyCode.C           = 67;
    KeyCode.V           = 86;

    usenamespace('editor.es5.consts').KeyCode = KeyCode;
})();
